services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sd_bots
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: virtual_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sd_bots -d virtual_dev"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
