"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-04-29 12:32:16.212587

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('from_agent', sa.String(length=128), nullable=False),
    sa.Column('to_agent', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_messages_from_agent'), ['from_agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_to_agent'), ['to_agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_topic'), ['topic'], unique=False)

    op.create_table('analyst_conversation_fragments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('mm_post_id', sa.String(length=64), nullable=False),
    sa.Column('asked_post_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('flushed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'mm_post_id', name='uq_analyst_conv_fragment_post')
    )
    with op.batch_alter_table('analyst_conversation_fragments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_conversation_fragments_task_id'), ['task_id'], unique=False)

    op.create_table('analyst_conversation_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'seq', name='uq_analyst_conv_step_seq')
    )
    with op.batch_alter_table('analyst_conversation_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_conversation_steps_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_conversation_steps_task_id'), ['task_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_level'), ['level'], unique=False)

    op.create_table('merge_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_key', sa.String(length=128), nullable=False),
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('task_external_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_branch', sa.String(length=256), nullable=False),
    sa.Column('target_branch', sa.String(length=256), nullable=False),
    sa.Column('author_username', sa.String(length=128), nullable=False),
    sa.Column('web_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approvals_count', sa.Integer(), nullable=False),
    sa.Column('approvals_required', sa.Integer(), nullable=False),
    sa.Column('pipeline_status', sa.String(length=16), nullable=False),
    sa.Column('pipeline_url', sa.String(length=1024), nullable=True),
    sa.Column('last_seen_comment_id', sa.String(length=64), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('last_pipeline_notified_status', sa.String(length=16), nullable=True),
    sa.Column('last_escalation_at', sa.DateTime(), nullable=True),
    sa.Column('ping_reviewers_at', sa.DateTime(), nullable=True),
    sa.Column('review_ping_sent', sa.Boolean(), nullable=False),
    sa.Column('review_thread_channel_id', sa.String(length=64), nullable=True),
    sa.Column('review_thread_root_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_autofix_attempts', sa.Integer(), nullable=False),
    sa.Column('pipeline_autofix_escalated', sa.Boolean(), nullable=False),
    sa.Column('iteration_pending_ci_sha', sa.String(length=64), nullable=True),
    sa.Column('iteration_ack_target', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_key', 'iid', name='uq_repo_iid')
    )
    with op.batch_alter_table('merge_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merge_requests_iid'), ['iid'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_requests_repo_key'), ['repo_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_requests_review_thread_root_id'), ['review_thread_root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_requests_task_external_id'), ['task_external_id'], unique=False)

    op.create_table('mr_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_key', sa.String(length=128), nullable=False),
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_username', sa.String(length=128), nullable=False),
    sa.Column('web_url', sa.String(length=1024), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('embed_model', sa.String(length=256), nullable=False),
    sa.Column('embed_dim', sa.Integer(), nullable=False),
    sa.Column('embed_norm', sa.Float(), nullable=False),
    sa.Column('embedding_blob', sa.LargeBinary(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_key', 'iid', name='uq_mr_history_repo_iid')
    )
    with op.batch_alter_table('mr_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mr_history_iid'), ['iid'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr_history_indexed_at'), ['indexed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr_history_repo_key'), ['repo_key'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker', sa.String(length=32), nullable=False),
    sa.Column('task_external_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('open_questions_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_repo_key', sa.String(length=128), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('agent_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_task_external_id'), ['task_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_tracker'), ['tracker'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('assignee_id', sa.String(length=128), nullable=True),
    sa.Column('reporter_id', sa.String(length=128), nullable=True),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('labels_json', sa.JSON(), nullable=False),
    sa.Column('links_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('external_status', sa.String(length=64), nullable=False),
    sa.Column('created_at_external', sa.DateTime(), nullable=True),
    sa.Column('updated_at_external', sa.DateTime(), nullable=True),
    sa.Column('internal_status', sa.String(length=32), nullable=False),
    sa.Column('target_repo_key', sa.String(length=128), nullable=True),
    sa.Column('dor_satisfied', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('awaiting_post_id', sa.String(length=64), nullable=True),
    sa.Column('awaiting_user_id', sa.String(length=64), nullable=True),
    sa.Column('awaiting_username', sa.String(length=128), nullable=True),
    sa.Column('awaiting_channel_id', sa.String(length=64), nullable=True),
    sa.Column('awaiting_dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('last_fragment_at', sa.DateTime(), nullable=True),
    sa.Column('coalesce_window_seconds', sa.Integer(), nullable=False),
    sa.Column('analyst_iteration_count', sa.Integer(), nullable=False),
    sa.Column('last_analyst_started_at', sa.DateTime(), nullable=True),
    sa.Column('analyst_deadline_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracker', 'external_id', name='uq_tracker_external_id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_awaiting_post_id'), ['awaiting_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_internal_status'), ['internal_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_tracker'), ['tracker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_tracker'))
        batch_op.drop_index(batch_op.f('ix_tasks_internal_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_external_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_awaiting_post_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_tracker'))
        batch_op.drop_index(batch_op.f('ix_plans_task_external_id'))
        batch_op.drop_index(batch_op.f('ix_plans_status'))
        batch_op.drop_index(batch_op.f('ix_plans_created_at'))
        batch_op.drop_index(batch_op.f('ix_plans_agent_key'))

    op.drop_table('plans')
    with op.batch_alter_table('mr_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mr_history_repo_key'))
        batch_op.drop_index(batch_op.f('ix_mr_history_indexed_at'))
        batch_op.drop_index(batch_op.f('ix_mr_history_iid'))

    op.drop_table('mr_history')
    with op.batch_alter_table('merge_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merge_requests_task_external_id'))
        batch_op.drop_index(batch_op.f('ix_merge_requests_status'))
        batch_op.drop_index(batch_op.f('ix_merge_requests_review_thread_root_id'))
        batch_op.drop_index(batch_op.f('ix_merge_requests_repo_key'))
        batch_op.drop_index(batch_op.f('ix_merge_requests_iid'))

    op.drop_table('merge_requests')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_level'))
        batch_op.drop_index(batch_op.f('ix_events_kind'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('analyst_conversation_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_conversation_steps_task_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_conversation_steps_kind'))

    op.drop_table('analyst_conversation_steps')
    with op.batch_alter_table('analyst_conversation_fragments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_conversation_fragments_task_id'))

    op.drop_table('analyst_conversation_fragments')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_topic'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_to_agent'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_from_agent'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_external_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_correlation_id'))

    op.drop_table('agent_messages')
    # ### end Alembic commands ###
