"""bus durable subscribers and lease

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-29 16:05:49.974414

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_subscriptions',
    sa.Column('agent_key', sa.String(length=128), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_key')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_until', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_agent_messages_to_agent_consumed_claimed', ['to_agent', 'consumed_at', 'claimed_until'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_messages_to_agent_consumed_claimed')
        batch_op.drop_column('claimed_until')

    op.drop_table('bus_subscriptions')
    # ### end Alembic commands ###
