"""fragment files_json

Revision ID: 0004
Revises: 0003
Create Date: 2026-04-30 14:59:10.103096

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing rows need a default for the NOT NULL — empty JSON list
    # matches the model's runtime default.
    with op.batch_alter_table('analyst_conversation_fragments', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'files_json', sa.JSON(), nullable=False,
            server_default=sa.text("'[]'"),
        ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyst_conversation_fragments', schema=None) as batch_op:
        batch_op.drop_column('files_json')

    # ### end Alembic commands ###
